### ISSUE TITLE
Please hear me out

### ISSUE THREAD

**Issue by JordyScript** [sfneal/users#26]
Since issues are turned of for the PyPDF3 repository you own, and i could find no other way to contact you, please allow me to reach out to you here. 

I've noticed that the excellent libraries PyPDF 1, 2, 3, and 4 are all suffering from lack of maintenance. PyPDF 1 and 2 have clearly been superseded and left behind, but it is unclear whether the community should rally behind PyPDF3 or PyPDF4, (or ideally combine efforts of PyPDF3 and 4) as both are not very actively developed, but not completely stagnant either. However since you have issues turned off, it seems like you are not looking for active collaboration on your fork of the library.

Now, since this is open source, you are of course not required to accept collaboration or give up your time to contribute to any open source library, but it would be helpful for the Python community if you made your position clear in the README.md of PyPDF3. What is the purpose of this repository to you? Is it just a repo you created to improve upon PyPDF2 for personal use and are you done with it now? Or do you want PyPDF3 to be(come) as generally useful and feature complete as possible and widely used by the community? Do you welcome collaboration, or do you encourage people to fork and supersede your library?

Currently, I don't know which library (PyPDF3 or PyPDF4) is more feature complete and bug free, nor do i know which should receive collaborative efforts, if any, or if another fork (PyPDF5?) should be attempted to revitalize the project. Forking yet another time is not my preferred course of action, as it increases fragmentation and confusion, but it may still be the best option depending on how you and the author of PyPDF4 feel about the respective prospects of your libraries. Another option could be transferring ownership of the repository and the PyPi package to someone else who is willing to further the development of the project in collaboration with the community.

I would like to hear your thoughts about this, and regardless of how you decide to lead your project, please make an attempt to communicate to the community your position (readme is probably the best place for that) so that we have clarity and can decide where to focus our efforts. 

Regardless, thank you for your development of PyPDF3.

**Comment by sfneal** [comment]
I'll get back to you on this later in the week, thanks for reaching out.
